#pragma once
class PeDirectory
{
private:
	HINSTANCE peInstance = NULL;
	HWND editHwnd[32] = {NULL};
	int editId[32] = {
		IDC_BTN_PE_DIRECTOR_DCB_RVA,
		IDC_BTN_PE_DIRECTOR_DCB_SIZE,
		IDC_BTN_PE_DIRECTOR_DRB_RVA,
		IDC_BTN_PE_DIRECTOR_DRB_SIZE,
		IDC_BTN_PE_DIRECTOR_ZY_RVA,
		IDC_BTN_PE_DIRECTOR_ZY_SIZE,
		IDC_BTN_PE_DIRECTOR_YC_RVA,
		IDC_BTN_PE_DIRECTOR_YC_SIZE,
		IDC_BTN_PE_DIRECTOR_AQZS_RVA,
		IDC_BTN_PE_DIRECTOR_AQZS_SIZE,
		IDC_BTN_PE_DIRECTOR_CDWB_RVA,
		IDC_BTN_PE_DIRECTOR_CDWB_SIZE,
		IDC_BTN_PE_DIRECTOR_TSXX_RVA,
		IDC_BTN_PE_DIRECTOR_TSXX_SIZE,
		IDC_BTN_PE_DIRECTOR_BQSY_RVA,
		IDC_BTN_PE_DIRECTOR_BQSY_SIZE,
		IDC_BTN_PE_DIRECTOR_QJZZ_RVA,
		IDC_BTN_PE_DIRECTOR_QJZZ_SIZE,
		IDC_BTN_PE_DIRECTOR_TLSB_RVA,
		IDC_BTN_PE_DIRECTOR_TLSB_SIZE,
		IDC_BTN_PE_DIRECTOR_JZXX_RVA,
		IDC_BTN_PE_DIRECTOR_JZXX_SIZE,
		IDC_BTN_PE_DIRECTOR_BDDR_RVA,
		IDC_BTN_PE_DIRECTOR_BDDR_SIZE,
		IDC_BTN_PE_DIRECTOR_IATB_RVA,
		IDC_BTN_PE_DIRECTOR_IATB_SIZE,
		IDC_BTN_PE_DIRECTOR_YCDR_RVA,
		IDC_BTN_PE_DIRECTOR_YCDR_SIZE,
		IDC_BTN_PE_DIRECTOR_COM_RVA,
		IDC_BTN_PE_DIRECTOR_COM_SIZE,
		IDC_BTN_PE_DIRECTOR_BL_RVA,
		IDC_BTN_PE_DIRECTOR_BL_SIZE
	};
public:
	BYTE * pointer = NULL;
public:
	PeDirectory();
	~PeDirectory();

	void creadPEDirectoryDialog(HINSTANCE PeInstance, BYTE *fpointer);
	friend INT_PTR CALLBACK PeDirectoryDialog(HWND hDlg, UINT iMessage, WPARAM wParam, LPARAM lParam);
};

