#pragma once
class PeOptional
{
private:
	HINSTANCE peInstance = NULL;
	int edit[30] = { IDC_PE_OPTIONAL_IMAGIC,
		IDC_PE_OPTIONAL_IMAJORLINKERVERSION,
		IDC_PE_OPTIONAL_MINORLINKERVERSION,
		IDC_PE_OPTIONAL_SIZEOFCODE,
		IDC_PE_OPTIONAL_SIZEOFINITIALIZEDDATA,
		IDC_PE_OPTIONAL_SIZEOFUNINITIALIZEDDATA,
		IDC_PE_OPTIONAL_ADDRESSOFENTRYPOINT,
		IDC_PE_OPTIONAL_BASEOFCODE,
		IDC_PE_OPTIONAL_BASEOFDATA,
		IDC_PE_OPTIONAL_IMAGEBASE,
		IDC_PE_OPTIONAL_SECTIONALIGNMENT,
		IDC_PE_OPTIONAL_FILEALIGNMENT,
		IDC_PE_OPTIONAL_MAJOROPERATINGSYSTEMVERSION,
		IDC_PE_OPTIONAL_MINOROPERATINGSYSTEMVERSION,
		IDC_PE_OPTIONAL_MAJORIMAGEVERSION,
		IDC_PE_OPTIONAL_MINORIMAGEVERSION,
		IDC_PE_OPTIONAL_MAJORSUBSYSTEMVERSION,
		IDC_PE_OPTIONAL_MINORSUBSYSTEMVERSION,
		IDC_PE_OPTIONAL_WIN32VERSIONVALUE,
		IDC_PE_OPTIONAL_SIZEOFIMAGE,
		IDC_PE_OPTIONAL_SIZEOFHEADERS,
		IDC_PE_OPTIONAL_CHECKSUM,
		IDC_PE_OPTIONAL_SUBSYSTEM,
		IDC_PE_OPTIONAL_DLLCHARACTERISTICS,
		IDC_PE_OPTIONAL_SIZEOFSTACKRESERVE,
		IDC_PE_OPTIONAL_SIZEOFSTACKCOMMIT,
		IDC_PE_OPTIONAL_SIZEOFHEAPRESERVE,
		IDC_PE_OPTIONAL_SIZEOFHEAPCOMMIT,
		IDC_PE_OPTIONAL_LOADERFLAGS,
		IDC_PE_OPTIONAL_NUMBEROFRVAANDSIZES };
	HWND editHwnd[30] = { NULL };
public:
	BYTE * pointer = NULL;
public:
	PeOptional();
	~PeOptional();
	void creadPEOptionalDialog(HINSTANCE PeInstance, BYTE *fpointer);

	friend INT_PTR CALLBACK PeOptionalDialog(HWND hDlg, UINT iMessage, WPARAM wParam, LPARAM lParam);
};

